// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRgkILVJx_-iqtaPkW1irmF6lPZdr48mo',
    appId: '1:816854486784:web:c5ff52377529427bdaade5',
    messagingSenderId: '816854486784',
    projectId: 'what-today-rice',
    authDomain: 'what-today-rice.firebaseapp.com',
    storageBucket: 'what-today-rice.firebasestorage.app',
    measurementId: 'G-FV6W1NRCM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXCwiZCNIe5GnsUT7Rq4gCh_rgFGjsmEg',
    appId: '1:816854486784:android:f7b18de5c0778747daade5',
    messagingSenderId: '816854486784',
    projectId: 'what-today-rice',
    storageBucket: 'what-today-rice.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj39hFlIZp-DH9f3KMpwdBIyhMZ59IRj4',
    appId: '1:816854486784:ios:6f16d451ab12eedfdaade5',
    messagingSenderId: '816854486784',
    projectId: 'what-today-rice',
    storageBucket: 'what-today-rice.firebasestorage.app',
    iosBundleId: 'com.example.whatTodayRice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj39hFlIZp-DH9f3KMpwdBIyhMZ59IRj4',
    appId: '1:816854486784:ios:99f26afcbecd865edaade5',
    messagingSenderId: '816854486784',
    projectId: 'what-today-rice',
    storageBucket: 'what-today-rice.firebasestorage.app',
    iosBundleId: 'com.example.flutterWhattodayrice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZS3u0kgTdz0BLoGXHlST5HN-mZG_Ronw',
    appId: '1:816854486784:web:98ba3642567ac428daade5',
    messagingSenderId: '816854486784',
    projectId: 'what-today-rice',
    authDomain: 'what-today-rice.firebaseapp.com',
    storageBucket: 'what-today-rice.firebasestorage.app',
    measurementId: 'G-J5VT5WR58D',
  );

}